name: CI
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-22.04
    container:
      image: librepcb/librepcb-cli:1.0.0-rc1
      options: --entrypoint /bin/bash
    steps:
    - uses: actions/checkout@v1
    # Note: Temporarily removed --minify-step because of 
    # https://github.com/LibrePCB/LibrePCB/pull/1226
    - run: librepcb-cli open-library --all --strict .
